# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypaltransaction',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='paypaltransaction',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
