# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaricom', '0002_auto_20180921_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100)),
                ('result_code', models.IntegerField()),
                ('mpesa_receipt_no', models.CharField(max_length=20)),
                ('transaction_date', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnsuccessfulTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100)),
                ('result_code', models.IntegerField()),
                ('result_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
