# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaricom', '0003_auto_20180922_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfultransfer',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
